### PR TITLE
[feature] switch-camera

### PR DESCRIPTION
**Pull request by MylesBorins**
Cause sometimes life throws you a curve ball and you need to use the camera on your cinema display.

### CODE REVIEW

**Comment by marcusramberg** [comment]
Seems like this should have been merged ages ago as well. Can you rebase it against latest, @TheAlphaNerd ?

**Comment by TheAlphaNerd** [comment]
Will do. I think there was some weirdness with this anyways, I'll check it
out in a minute

**Comment by TheAlphaNerd** [comment]
rebased... don't have as setup with two camera's to test off of though. Will be able to test at office tomorrow.

**Comment by marcusramberg** [comment]
@TheAlphaNerd I don't have such a setup either, will hold off until you test from the office then merge.

**Pull request closed without merging**
