### PR TITLE
Default to 0.0.0.0 instead of localhost

### PR DESCRIPTION
**Pull request by bennlich**
It looks like `hapi` treats a `localhost` domain as "respond to requests coming from this machine only." I'm thinking the sample local.json should probably allow requests from other machines by default too?

I was scratching my head for a while wondering, why isn't the server responding to anything, and also not providing any errors?

### CODE REVIEW

**Comment by jasonrhodes** [comment]
`local.json` is meant to have defaults for local development, with the expectation that you will have to modify those for a `production.json` file, so I don't think it makes sense to change this value.

**Comment by bennlich** [comment]
Ah, k. If it makes any difference, 0.0.0.0 would work in both cases (responds to localhost *and* external requests). Also, the newer version of hapi [defaults to the operating system hostname, and falls back to localhost](http://hapijs.com/api#serverinfo).

Do you think it would be better to add a bit to the readme about needing to change the host to 0.0.0.0 when deploying?

**Comment by jasonrhodes** [comment]
0.0.0.0 is usually too permissive for someone doing local development, allowing anyone on the same network to reach you, so you don't want to default to that. And when deploying, you usually want to broadcast to a local port and then proxy to port 80 of your host IP, for security, so changing to 0.0.0.0 is probably not the recommended way of deploying. 

DigitalOcean has some good articles about this kind of set up, if anybody is interested, e.g. https://www.digitalocean.com/community/tutorials/how-to-host-multiple-node-js-applications-on-a-single-vps-with-nginx-forever-and-crontab

**Comment by bennlich** [comment]
Cool! Thanks!

**Comment by bennlich** [comment]
@jasonrhodes I've been setting up a server like the one described in the link you pasted, and one thing that seems kind of tricky is that nginx passes the whole proxied path to the node server. So if I want to run a meatspace at `somedomain.com/my-meatspace`, I guess I have to edit the meatspace server to expect the /my-meatspace route? If I use nginx to rewrite the path, all the resources get borked (because they're requested from `somedomain.com/` and don't get routed to the meatspace server). Do you have any tips here?

**Comment by bennlich** [comment]
I ended up solving this problem by changing the absolute urls in [layout.jade](https://github.com/meatspaces/meatspace-chat-v2/blob/master/views/layout.jade) to relative urls (by deleting the initial `/`). Is this something worth merging into master?

**Pull request closed without merging**
